### ISSUE TITLE
Pod IPs removed from EndpointSlices for non-headless services in v0.15

### ISSUE THREAD

**Issue by t0lya** [submariner-io/lighthouse#1267]
I have a question regarding [Aggregate Service Import enhancement proposal](https://github.com/submariner-io/enhancements/blob/devel/lighthouse/aggregate-service-import.md) which was implemented in https://github.com/submariner-io/lighthouse/pull/1144 and shipped in Submariner release 0.15. This change removed pod IP endpoints from EndpointSlice documents for non-headless ClusterIP services. 

E.g., Endpoints list contains ClusterIP (address 10.0.0.1 in example). Before 0.15, endpoints contained list of pod IPs.
```
addressType: IPv4
apiVersion: discovery.k8s.io/v1
endpoints:
- addresses:
  - 10.0.1.1
  conditions:
    ready: true
kind: EndpointSlice
metadata:
  labels:
    endpointslice.kubernetes.io/managed-by: lighthouse-agent.submariner.io
    lighthouse.submariner.io/is-headless: "false"
    lighthouse.submariner.io/sourceNamespace: default
    multicluster.kubernetes.io/service-name: prometheus-node-exporter
    multicluster.kubernetes.io/source-cluster: cluster-a
    submariner-io/clusterID:  cluster-a
    submariner-io/originatingNamespace: default
  name: prometheus-node-exporter-default-cluster-a
  namespace: submariner-k8s-broker
ports:
- name: metrics
  port: 9100
  protocol: TCP
```

What was the reasoning behind this change and why is it needed? I could not find the reasoning while reading through [Aggregate Service Import enhancement proposal](https://github.com/submariner-io/enhancements/blob/devel/lighthouse/aggregate-service-import.md). I do not see such a requirement on EndpointSlices in [KEP 1645](https://github.com/kubernetes/enhancements/blob/master/keps/sig-multicluster/1645-multi-cluster-services-api/README.md#endpointslice).

My team has a use-case for getting the list of ready endpoints for a given ClusterIP service across all connected clusters. We currently implement this by querying the ready endpoints in the EndpointSlice document on the broker cluster. We are trying to figure out how to preserve this use-case while upgrading Submariner to 0.15.
