### ISSUE TITLE
ServiceGlobalIPUnavailable issue with globalnet enabled

### ISSUE THREAD

**Issue by rastislavs** [submariner-io/lighthouse#368]
**What happened**:
I joined 2 clusters into a topology with globalnet enabled. In one of them, I created a deployment, exposed it via ClusterIP service and exported it via `subctl export`. The generated ServiceExport's status says `Service doesn't have a global IP yet`. The ServiceImport in the other cluster is not created.
```
  status:
    conditions:
    - lastTransitionTime: "2020-11-11T15:44:44Z"
      message: Service doesn't have a global IP yet
      reason: ServiceGlobalIPUnavailable
      status: "False"
      type: Initialized
```

**What you expected to happen**:
Status of the ServiceExport OK, ServiceImport created in the other cluster.

**How to reproduce it (as minimally and precisely as possible)**:
In cluster 1:
```
subctl deploy-broker --globalnet --globalnet-cidr-range=100.64.0.0/16
subctl join broker-info.subm
```
In cluster 2:
```
subctl join broker-info.subm
```

**Anything else we need to know?**:

**Environment**:
- Submariner version (use `subctl version`): v0.7.0
- Kubernetes version (use `kubectl version`): v1.18.10
- Cloud provider or hardware configuration: Kubermatic Kubernetes Platform on AWS
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.5 LTS
- Kernel (e.g. `uname -a`): 5.4.0-1029-aws
- Install tools: `subctl`
- Network plugin and version (if this is a network-related bug): canal-flannel
- Others:
