### ISSUE TITLE
`serviceimport` and `serviceexport` point to the old CRDs

### ISSUE THREAD

**Issue by nyechiel** [submariner-io/lighthouse#418]
**What happened**:

After upgrading a cluster from v0.7 to v0.8 with a previously exported service, I noticed that Lighthouse converted the `ServiceExport` to the MCS CRD as expected, but it looks like `serviceimports` and `serviceexports` still point to the old (Lighthouse) CRD:

```
$ kubectl get serviceexports
No resources found in default namespace.
```

It looks like both the new and old CRDs use the same plural/singular:

```
conversion:
    strategy: None
  group: multicluster.x-k8s.io
  names:
    kind: ServiceImport
    listKind: ServiceImportList
    plural: serviceimports
    shortNames:
    - svcim
    singular: serviceimport
  scope: Namespaced
  versions:
```

What's more interesting: even after manually deleting the old Lighthouse CRDs, it seems like we are still pointing at the old ones:

```
$ kubectl delete crd serviceimports.lighthouse.submariner.io serviceexports.lighthouse.submariner.io 

$ kubectl get ServiceImports -A
Error from server (NotFound): Unable to list "lighthouse.submariner.io/v2alpha1, Resource=serviceimports": the server could not find the requested resource (get serviceimports.lighthouse.submariner.io)
```

**What you expected to happen**:

`serviceimport` and `serviceexport` to point at the new MCS CRDs in 0.8 clusters, especially after the old Lighthouse CRDs no longer present in the cluster. 

**How to reproduce it (as minimally and precisely as possible)**:

1. Deploy Submariner v0.7 on kind, create and export a service in one of the connected clusters
2. Upgrade the clusterset to Submariner v0.8 (I used rc1 in my testing)

**Anything else we need to know?**:

The service seems to be exported properly after the upgarde; this is more of a UX thing AFAICT but I still find it confusing. 

```
$ kubectl get serviceexports.multicluster.x-k8s.io
NAME    AGE
nginx   19m
```
