### ISSUE TITLE
Option to integrate lighthouse plugin to cluster coredns

### ISSUE THREAD

**Issue by juju812** [submariner-io/lighthouse#954]
In current implementation, multicluster DNS discovery is handled by dedicated deployment `submariner-lighthouse-coredns`.  When user want to access service imported from another cluster, `clusterset.local` domain has to be specified, and then forwarded to `submariner-lighthouse-coredns` service.

But for our usecase, we prefer to use `<svc-name>.<namespace>`  pattern, and we do not care whether the service is in-cluster or imported. This can be achived by integrate lighthouse plugin to cluster coredns. `Kubernetes` plugin can handle `cluster.local` domain first, if not found, user pod try to search `clusterset.local` domain, then goes to `lighthouse` plugin.

One demo approach as below(coredns deployment and clusterrole settings omitted):

- Add lighthouse support to cluster coredns
  - [edit `plugin.cfg`](https://coredns.io/2017/07/25/compile-time-enabling-or-disabling-plugins/)，add line `lighthouse:github.com/submariner-io/lighthouse/coredns/plugin` after `kubernetes` plugin, then recomplie coredns
- Edit `coredns`  Corefile, move `lighthouse` plugin to `.:53` block

```
# remove lighthouse config of clusterset.local:53
.:53 {
    ...
    kubernetes cluster.local in-addr.arpa ip6.arpa {
       pods insecure
       fallthrough in-addr.arpa ip6.arpa
       ttl 30
    }
    lighthouse clusterset.local {    # add lighthouse config
       fallthrough
    }
    prometheus :9153
    ...
}
```

- Add `clusterset.local` domains to DNS searchs of pod

```yaml
    spec:
      dnsPolicy: "ClusterFirst"
      dnsConfig:
        searches:
          - default.svc.clusterset.local  # namespace should be dynamically generated here
          - svc.clusterset.local
          - clusterset.local
```

**What would you like to be added**: option to integrate lighthouse plugin to cluster coredns while deploying submariner.

**Why is this needed**: to support usecase described above, with less customization.
